salaboy/environment-kingsand-staging

env/requirements.yaml
Promote ttc-rb-english-campaign to version 1.0.24
=> ttc-rb-english-campaign to 1.0.24

env/requirements.yaml
Promote ttc-rb-english-campaign to version 1.0.26
=> ttc-rb-english-campaign to 1.0.26

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.10
=> ttc-connectors-reward to 1.0.10

env/requirements.yaml
Promote ttc-connectors-processing to version 1.0.10
=> ttc-connectors-processing to 1.0.10

env/requirements.yaml
Promote ttc-dashboard-ui to version 0.0.32
=> ttc-dashboard-ui to 0.0.32

env/requirements.yaml
The command `jx delete app` was run by msalatino and it generated this Pull Request
=> Delete application ttc-dashboard-ui from this environment

env/requirements.yaml
Promote ttc-rb-english-campaign to version 1.0.29
=> ttc-rb-english-campaign to 1.0.29

env/requirements.yaml
Promote ttc-rb-english-campaign to version 1.0.31
=> ttc-rb-english-campaign to 1.0.31

env/requirements.yaml
Promote ttc-connectors-dummytwitter to version 1.0.30
=> ttc-connectors-dummytwitter to 1.0.30

env/requirements.yaml
Promote ttc-query-campaign to version 1.0.19
=> ttc-query-campaign to 1.0.19

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.11
=> ttc-connectors-reward to 1.0.11

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.12
=> ttc-connectors-reward to 1.0.12

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.13
=> ttc-connectors-reward to 1.0.13

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.14
=> ttc-connectors-reward to 1.0.14

env/requirements.yaml
Promote ttc-rb-english-campaign to version 1.0.34
=> ttc-rb-english-campaign to 1.0.34

env/requirements.yaml
Promote ttc-connectors-processing to version 1.0.15
=> ttc-connectors-processing to 1.0.15

env/requirements.yaml
Promote ttc-infra-gateway to version 1.0.11
=> ttc-infra-gateway to 1.0.11

env/requirements.yaml
Promote ttc-query-campaign to version 1.0.21
=> ttc-query-campaign to 1.0.21

env/requirements.yaml
Promote ttc-connectors-reward to version 1.0.16
=> ttc-connectors-reward to 1.0.16

env/requirements.yaml
Promote ttc-query-campaign to version 1.0.22
=> ttc-query-campaign to 1.0.22

env/requirements.yaml
Promote ttc-query-campaign to version 1.0.23
=> ttc-query-campaign to 1.0.23

env/requirements.yaml
Promote ttc-dashboard-ui to version 0.0.34
=> ttc-dashboard-ui to 0.0.34

env/requirements.yaml
Promote ttc-rb-alfresco-campaign to version 1.0.3
=> ttc-rb-alfresco-campaign to 1.0.3

env/requirements.yaml
Promote ttc-rb-alfresco-campaign to version 1.0.4
=> ttc-rb-alfresco-campaign to 1.0.4

env/requirements.yaml
The command `jx delete app` was run by msalatino and it generated this Pull Request
=> Delete application ttc-rb-alfresco-campaign from this environment

env/requirements.yaml
Promote showcase-admin-tool to version 0.0.9
=> showcase-admin-tool to 0.0.9

env/requirements.yaml
The command `jx delete app` was run by msalatino and it generated this Pull Request
=> Delete application ttc-connectors-processing from this environment
